# Generated by Django 4.2.7 on 2025-10-11 08:06

from django.db import migrations
from django.utils import timezone


def set_default_due_dates(apps, schema_editor):
    Task = apps.get_model('todo', 'Task')
    # Set due_date to today for all existing tasks that have null due_date
    for task in Task.objects.filter(due_date__isnull=True):
        task.due_date = timezone.now().date()
        task.save()


def reverse_set_default_due_dates(apps, schema_editor):
    # This migration is not reversible
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_alter_task_options'),
    ]

    operations = [
        migrations.RunPython(set_default_due_dates, reverse_set_default_due_dates),
    ]
